### PR TITLE
Show siya value formatted

### PR DESCRIPTION
**Pull request by mjparme**
Added another text box next to siya that shows the entered siya value formatted according to users choice. This makes it easier to see what value you are entering when the numbers start getting big and you have tons of zeroes.

screen shot 2016-11-29 at 2 05 57 pm

### CODE REVIEW

**Comment by alexbonjour** [comment]
Thanks! What I really want is to reformat the input box according to the formatting style.   That requires that I can read 15400T and interpret it as 15400e12.

Any interest in taking a shot?

**Comment by mjparme** [comment]
Strange you say that because I had the same idea and was working up the motivation to tackle it. Your email got me motivated. I believe I have it done; however, I still need to test it. Once I get it all tested I will get it committed to my branch and submit a pull request.

**Comment by alexbonjour** [comment]
Sweet. :)   I look forward to it.

On Mon, Dec 19, 2016 at 11:14 AM, Michael Parmeley <notifications@github.com

**Comment by mjparme** [comment]
I have pushed the change up to my branch, you can get it with the previous pull request. I did it on the same branch, I am new to "git" (been using subversion for many years) so didn't realize it was a git best practice to do a change per branch.

If you need this change separated from my previous change let me know and I will see what I can do.

**Comment by alexbonjour** [comment]
I worked with this but I can't get the second text box to show up well on both desktops and mobile.   I'm thinking of taking out the extra field and keeping your new formatting rules.   Thoughts?

**Pull request closed without merging**
